port: 7899
socks-port: 7898
redir-port: 0
tproxy-port: 0
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 127.0.0.1:9097

proxies: 
  - name: "直连"
    type: direct
    udp: true
proxy-groups: 
  - name: 空白配置
    type: "select"
    proxies:
      - DIRECT
rules:
  - MATCH,DIRECT
